name: model-training

on: [push]

jobs:
  train-current:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          pip install -r requirements.txt
          dvc repro train

          dvc plots diff master --targets p.json
