name: model-training

on: [push]

jobs:
  train-current:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: prepare current version report
        run: |
          pip install -r requirements.txt
          dvc repro train

          git fetch --prune

          dvc plots diff master --targets p.json
